apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-busybox-deployment
  name: nginx-busybox-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-busybox-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-busybox-deployment
    spec:
      containers:
      - image: gcr.io/dynamic-circle-431306-h3/custom-nginx-busybox-deployment-image:latest
        imagePullPolicy: Always
        name: nginx-1
        ports:  
        - containerPort: 80
      - image: busybox:latest
        imagePullPolicy: Always
        name: busybox
        command:
        - sh
        - -c
        - echo Hello from BusyBox! && sleep 3600
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "nginx"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
